# Generated by Django 6.0.1 on 2026-02-17 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_id_volunteer"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteer",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="volunteer_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("donor", "Donor"),
                    ("claimant", "Claimant"),
                    ("volunteer", "Volunteer"),
                    ("admin", "Admin"),
                ],
                default="claimant",
                max_length=10,
            ),
        ),
    ]
