# Generated by Django 6.0.1 on 2026-02-17 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_listing_servings_alter_claim_id_alter_listing_id"),
        ("users", "0004_volunteer_user_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="PickupAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("picked_up", "Picked Up"),
                            ("delivered", "Delivered"),
                        ],
                        default="assigned",
                        max_length=15,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pickup_assignments",
                        to="listings.claim",
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pickup_assignments",
                        to="users.volunteer",
                    ),
                ),
            ],
        ),
    ]
