# Generated by Django 6.0.1 on 2026-02-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_alter_claim_id_alter_listing_id_pickupassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="pickupassignment",
            name="pickup_otp",
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
