# Generated by Django 6.0.1 on 2026-02-18 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_pickupassignment_pickup_otp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pickupassignment",
            name="pickup_otp",
        ),
        migrations.CreateModel(
            name="PickupOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=6)),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp",
                        to="listings.pickupassignment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pickup OTP",
                "verbose_name_plural": "Pickup OTPs",
            },
        ),
    ]
